// examples/vite-qwik/src/components/ui/btn.jsx
import { component$, useStylesScoped$, Slot } from '@builder.io/qwik'
import styles from 'winduum/src/ui/btn.css?inline'

export default component$((props) => {
    useStylesScoped$(styles);

    return (
        <button className="ui-btn" {...props}>
            <Slot />
        </button>
    );
});

// examples/nuxt/components/Ui/Btn.vue
<script setup>
    defineProps({
        variant: String,
        state: String,
        size: String
    })
</script>

<template>
    <button class="ui-btn" type="button" :class="[variant, state, size]">
        <slot></slot>
    </button>
</template>

<style scoped>
    @import "winduum/src/ui/btn.css";
</style>
