// examples/nuxt/components/Ui/Btn.vue
<script setup>
    defineProps({
        variant: String,
        state: String,
        size: String
    })
</script>

<template>
    <button class="ui-btn" type="button" :class="[variant, state, size]">
        <slot></slot>
    </button>
</template>

<style scoped>
    @import "winduum/src/ui/btn.css";
</style>

// examples/vite-qwik/src/components/ui/btn.tsx
import type { QwikIntrinsicElements } from '@builder.io/qwik';
import { component$, useStylesScoped$, Slot } from '@builder.io/qwik';
import styles from 'winduum/src/ui/btn.css?inline';

export type HTMLButtonProps = QwikIntrinsicElements['button'];

export default component$((props: HTMLButtonProps) => {
    useStylesScoped$(styles);

    return (
        <button class="ui-btn" {...props}>
            <Slot />
        </button>
    );
});
