// examples/vite-react/src/App.jsx
import { useState } from 'react'
import reactLogo from './assets/react.svg'
import './App.css'

import UiBtn from './components/ui/Btn.jsx'

function App () {
    const [count, setCount] = useState(0)

    return (
        <div className="App">
            <div className="flex justify-center">
                <a href="https://vitejs.dev" target="_blank">
                    <img src="/vite.svg" className="logo" alt="Vite logo" />
                </a>
                <a href="https://reactjs.org" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo" />
                </a>
            </div>
            <h1>Vite + React</h1>
            <div className="card p-xl space-y-8">
                <UiBtn onClick={() => setCount((count) => count + 1)}>count is {count}</UiBtn>
                <p>
          Edit <code>src/App.jsx</code> and save to test HMR
                </p>
            </div>
            <p className="read-the-docs">
        Click on the Vite and React logos to learn more
            </p>
        </div>
    )
}

export default App

// examples/vite-qwik/src/app.jsx
import { component$, useSignal } from '@builder.io/qwik'

import qwikLogo from './assets/qwik.svg'
import './app.css'
import UiBtn from './components/ui/Btn.jsx'

export const App = component$(() => {
    const count = useSignal(0)

    return (
        <>
            <div class="flex justify-center">
                <a href="https://vitejs.dev" target="_blank">
                    <img src="/vite.svg" class="logo" alt="Vite logo" />
                </a>
                <a href="https://qwik.builder.io" target="_blank">
                    <img src={qwikLogo} class="logo qwik" alt="Qwik logo" />
                </a>
            </div>
            <h1>Vite + Qwik</h1>
            <div class="card">
                <UiBtn onClick$={() => count.value++}>count is {count.value}</UiBtn>
                <p>
          Edit <code>src/app.jsx</code> and save to test HMR
                </p>
            </div>
            <p class="read-the-docs">
        Click on the Vite and Qwik logos to learn more
            </p>
        </>
    )
})
